version: "3.7"
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myfirstdatabase
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
    ports:
      - 13306:3306

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - workbench-data:/config
    ports:
      - 13000:3000
  
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    environment:
      APP.ANONYMOUSACCESSENABLED: false
    volumes:
      - ./cloudbeaver:/opt/cloudbeaver/workspace
    ports: 
      - 18978:8978
volumes:
  mysql-data:
  mysql-log:
  workbench-data:
  cloudbeaver-data: